#Контейнер для auth сервиса
services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: lunary-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - auth-service
    networks:
      - lunary-network

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: lunary-auth
    ports:
      - "8081:8081"
    env_file:
    - ./services/auth-service/.env
    depends_on:
      - postgres
    volumes:
      - ./services/auth-service/migrations:/app/migrations
    command: ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/auth-service"]
    networks:
      - lunary-network
  
  postgres:
    image: postgres:15
    container_name: lunary-postgres
    restart: always
    environment:
      POSTGRES_DB: lunary_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - lunary-pgdata:/var/lib/postgresql/data
    networks:
      - lunary-network 

volumes:
  lunary-pgdata:

networks:
  lunary-network: