#Контейнер для auth сервиса
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lunary-postgres
    restart: always
    environment:
      POSTGRES_DB: lunary_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./services/auth-service
    container_name: lunary-auth
    env_file:
      - ./services/auth-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  pgdata: