# Dockerfile для API Gateway (Go)
FROM golang:1.24.3

WORKDIR /app

# Кэшируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники
COPY . .

# Собираем бинарник
RUN go build -o api-gateway ./cmd

# Устанавливаем порт (если используется, не обязательно)
EXPOSE 8080

# Запуск
CMD ["./api-gateway"]