# ---------- Builder stage ----------
FROM golang:1.24.2 AS builder

WORKDIR /app

# Кэшируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники
COPY . .

# Собираем бинарник (предположим, у тебя main.go в ./cmd/main.go)
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api-gateway ./cmd/main.go

# ---------- Final stage ----------
FROM alpine:latest

# Устанавливаем сертификаты (для HTTPS)
RUN apk --no-cache add ca-certificates

WORKDIR /app

# Копируем бинарник из builder stage
COPY --from=builder /app/api-gateway .

# Указываем порт (по желанию)
EXPOSE 8080

# Запуск
CMD ["./api-gateway"]